language: node_js
dist: trusty
sudo: false
node_js: 10
cache:
  directories:
  - client/node_modules
install:
- npm install --prefix=client
script:
- npm run build --prefix=client
before_deploy:
- openssl aes-256-cbc -K $encrypted_bc2ea1f0e88d_key -iv $encrypted_bc2ea1f0e88d_iv
  -in deploy/client-secret.json.enc -out deploy/client-secret.json -d
deploy:
  provider: gae
  keyfile: deploy/client-secret.json
  project: hakurei-expo
  skip_cleanup: true
  on: develop
